language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
services:
  - docker
before_install:
  - docker login -e='admin@goatse.cx' -u='_json_key' -p="${GCR_KEY}"
script:
  - docker build -t "gcr.io/goonswarm-1303/bads:$(git rev-parse --short HEAD)" .
after_script:
  - docker push "gcr.io/goonswarm-1303/bads:$(git rev-parse --short HEAD)"
